FROM python
COPY . .
RUN pip install -r requirements.txt
ENV CONNECTION_STRING "YOURCONNECTIONSTRINGTOCOSMOS"
ENV DB_NAME "DATABASENAME"
ENV COLLECTION_NAME "COLLECTIONNAME"
ENV BATCH_SIZE 100
ENV DEVICE_ID 'DEV1'
CMD python setup.py